#language: minimal
language: bash

dist: bionic

services:
  - docker

env:
  - UBUNTU_DOCKER_IMAGE=ubuntu:18.04 HAPROXY_MAIN_VERSION=2.0
  - UBUNTU_DOCKER_IMAGE=ubuntu:18.04 HAPROXY_MAIN_VERSION=1.9
  - UBUNTU_DOCKER_IMAGE=ubuntu:18.04 HAPROXY_MAIN_VERSION=1.8

before_install:
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get -y install bats

install:
  - cd dockerfiles/apache && make build-without-cache && cd ../../
  - cd dockerfiles/haproxy && make build-without-cache && cd ../../

script:
  - make test

after_script:
  - make clean

notifications:
  email:
    - haproxy.cert.otf.travis@gmail.com

