#language: minimal
language: bash

dist: bionic

services:
  - docker

env:
  - HAPROXY_MAIN_VERSION=2.0
  - HAPROXY_MAIN_VERSION=1.9
  - HAPROXY_MAIN_VERSION=1.8

before_install:
  - sudo apt-get update && sudo apt-get -y install bats

install:
  - cd dockerfiles/apache && make build-without-cache && cd ../../
  - cd dockerfiles/haproxy && make build-without-cache && cd ../../

#before_script:
#  - 

script:
  - make test

after_script:
  - make clean

notifications:
  email:
    - haproxy.cert.otf.travis@gmail.com

