language: bash

dist: bionic

services:
  - docker

before_install:
  - sudo cat /etc/apt/sources.list
  - sudo ls /etc/apt/sources.list.d/
  - sudo cat /etc/apt/sources.list.d/pgdg.list
  - travis_retry sudo apt-get update
  - travis_retry sudo apt-get -y install bats

install:
  - export UBUNTU_DOCKER_IMAGE=ubuntu:latest
  #- export HAPROXY_MAIN_VERSION=2.0
  - |-
    LATEST_PPA_REPO=$(curl -s -H 'Accept: application/json' 'https://launchpad.net/api/1.0/~vbernat/ppas' | jq -r '.entries[].name' | sort --version-sort | tail -n 1 | cut -d'-' -f2)
  - export HAPROXY_MAIN_VERSION=$LATEST_PPA_REPO
  - echo $HAPROXY_MAIN_VERSION
  - git config remote.origin.fetch +refs/heads/*:refs/remotes/origin/*
  - git fetch
  - git checkout master
  - cd dockerfiles/apache
  - travis_retry make build-without-cache
  - cd "$TRAVIS_BUILD_DIR"
  - cd dockerfiles/haproxy
  - travis_retry make build-without-cache
  - cd "$TRAVIS_BUILD_DIR"

script:
  - make test

after_script:
  - make clean

notifications:
  email:
    - haproxy.cert.otf.travis@gmail.com

