
version: "3"
services:

  haproxy:
    hostname: haproxy
    image: bjoernbessert/haproxy-cert-otf
    depends_on:
      - apache
    ports:
      - "80:80/tcp"
      - "443:443/tcp"

  apache:
    hostname: apache
    image: bjoernbessert/apache-cert-otf

